use std::fmt::Write;

use crate::agent::ReviewFinding;
use crate::provider::ProviderUsage;
use crate::review::ReviewOutput;

const MARKER: &str = "<!-- cururu:summary -->";

pub const fn marker() -> &'static str {
    MARKER
}

pub fn render_summary_comment(output: &ReviewOutput) -> String {
    let mut out = String::new();
    out.push_str(MARKER);
    out.push_str("\n## 🐸 Cururu review\n\n");

    let _ = writeln!(out, "**Model:** `{}`  ", output.model);
    let _ = writeln!(
        out,
        "**Files reviewed:** `{}`  ",
        output.review.files_reviewed
    );
    let _ = write!(out, "**Findings:** `{}`\n\n", output.review.findings.len());

    if !output.context_files.is_empty() {
        let _ = write!(
            out,
            "**Context files:** `{}`\n\n",
            output.context_files.join(", ")
        );
    }

    if output.show_usage
        && let Some(ref usage) = output.usage
    {
        render_usage(usage, output.show_cost, &mut out);
    }

    if output.review.findings.is_empty() {
        out.push_str("No high-confidence issues found.\n");
    } else {
        out.push_str("| Severity | File | Line | Finding | Suggestion |\n");
        out.push_str("|---|---|---:|---|---|\n");
        for finding in &output.review.findings {
            out.push_str(&render_finding_row(finding));
        }
    }

    out.push_str("\n> Generated by `cururu`. Treat this as an assistant review, not a replacement for human review.\n");
    out
}

fn render_usage(usage: &ProviderUsage, show_cost: bool, out: &mut String) {
    out.push_str("**Tokens:** ");
    let _ = write!(
        out,
        "{} prompt + {} completion = {} total",
        usage.prompt_tokens, usage.completion_tokens, usage.total_tokens,
    );
    if usage.cached_tokens > 0 {
        let _ = write!(out, " ({} cached)", usage.cached_tokens);
    }
    if usage.reasoning_tokens > 0 {
        let _ = write!(out, " ({} reasoning)", usage.reasoning_tokens);
    }
    out.push_str("  \n");

    if show_cost && let Some(cost) = usage.cost {
        let _ = write!(out, "**Cost:** `${cost:.6}`\n\n");
    }
}

fn render_finding_row(f: &ReviewFinding) -> String {
    let line_str = f.line.map_or_else(|| "-".to_string(), |v| v.to_string());
    format!(
        "| {} | `{}` | {} | {} | {} |\n",
        escape_md(&f.severity),
        escape_md(&f.path),
        line_str,
        escape_md(&f.message),
        escape_md(&f.suggestion),
    )
}

fn escape_md(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}
