use crate::agent::{ReviewFinding, ReviewResult};

const MARKER: &str = "<!-- pullfrog-rs:summary -->";

pub fn marker() -> &'static str { MARKER }

pub fn render_summary_comment(result: &ReviewResult) -> String {
    let mut out = String::new();
    out.push_str(MARKER);
    out.push_str("\n## 🐸 Pullfrog-rs review\n\n");
    out.push_str(&format!("**Model:** `{}`  \n", result.model));
    out.push_str(&format!("**Files reviewed:** `{}`  \n", result.files_reviewed));
    out.push_str(&format!("**Findings:** `{}`\n\n", result.findings.len()));

    if result.findings.is_empty() {
        out.push_str("No high-confidence issues found.\n");
        return out;
    }

    out.push_str("| Severity | File | Line | Finding | Suggestion |\n");
    out.push_str("|---|---|---:|---|---|\n");
    for finding in &result.findings {
        out.push_str(&render_finding_row(finding));
    }

    out.push_str("\n> Generated by `pullfrog-rs`. Treat this as an assistant review, not a replacement for human review.\n");
    out
}

fn render_finding_row(f: &ReviewFinding) -> String {
    format!(
        "| {} | `{}` | {} | {} | {} |\n",
        escape_md(&f.severity),
        escape_md(&f.path),
        f.line.map_or("-".to_string(), |v| v.to_string()),
        escape_md(&f.message),
        escape_md(&f.suggestion),
    )
}

fn escape_md(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}
